
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow
  template:
    metadata:
      labels:
        app: taskflow
    spec:
      containers:
        - name: taskflow-container
          image: k8s-mini-web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            